name: Update Calendar
on:
  schedule:
    - cron:  '0 */12 * * *'  # Run twice a day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'main'  # Specify the branch to checkout

    - name: Setup Python
      uses: actions/setup-python@v4.7.0

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit and push to main
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Calendar"
        git push

    - name: Checkout gh-pages branch
      run: |
        git fetch
        git checkout gh-pages
        git pull origin gh-pages

    - name: Move ICS file to gh-pages
      run: |
        cp forejt.ics ./  # adjust the path as needed

    - name: Commit and push to gh-pages
      run: |
        git add -A
        git commit -m "Update Calendar ICS file"
        git push origin gh-pages
