name: Update Calendar
on:
  schedule:
    - cron:  '0 */12 * * *' # Run twice a day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout
    - name: Set up Python
      uses: actions/setup-python
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install =r requirements.txt
    - name: Run script
      run: python main.py
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Calendar"
        git push
