name: Update Calendar Job
on:
  schedule:
    - cron: "2 6 * * *" # run daily
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: "./forejt"

      - name: Setup Python
        uses: actions/setup-python@v4.7.0

      - name: Install dependencies
        run: pip install -r ./forejt/requirements.txt
        working-directory: ./

      - name: Run Tests
        run: pytest ./forejt/tests.py # Replace with your actual test command

      - name: Run script
        run: python ./forejt/main.py

      - name: Commit and push to main
        run: |
          cd ./forejt
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Update Calendar" || true  # Will not fail if there's nothing to commit
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: './gh-pages'
        
      - name: Check if ICS file is different
        id: diffcheck
        run: |
          diff ./forejt/forejt.ics ./gh-pages/forejt.ics || echo "changed=true" >> $GITHUB_ENV
        continue-on-error: true  # The diff command will fail if files are different. This makes sure the workflow continues.

      - name: Move ICS file to gh-pages if different
        if: env.changed == 'true'
        run: cp ./forejt/forejt.ics ./gh-pages/

      - name: Commit and push to gh-pages if different
        if: env.changed == 'true'
        run: |
          cd ./gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add forejt.ics
          git commit -m "Update Calendar ICS file"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
