name: Update Calendar Job
on:
  schedule:
    - cron: "2 21 * * *" # run daily, uncomment when you want to run the job
  push:
    branches:
      - main # change to main when you want to run the job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: "main"
          path: "./forejt"

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r ./forejt/requirements.txt
        working-directory: ./

      - name: Run Tests
        run: pytest ./forejt/tests.py

      - name: Run script
        run: python ./forejt/main.py

      - name: Debug List Files
        run: |
          ls -la ./forejt/
          ls -la .

      
      - name: Upload forejt.ics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: forejt-ics
          path: ./forejt.ics

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: './gh-pages'

      - name: Download forejt.ics from artifact
        uses: actions/download-artifact@v3
        with:
          name: forejt-ics
          path: ./artifacts/
        
      - name: Check if ICS file is different
        id: diffcheck
        run: |
          echo "Comparing ./artifacts/forejt.ics with ./gh-pages/forejt.ics"
          diff ./artifacts/forejt.ics ./gh-pages/forejt.ics || echo "changed=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Display changed status
        run: echo "Changed status is ${{ env.changed }}"

      - name: Move ICS file to gh-pages if different
        if: env.changed == 'true'
        run: cp ./artifacts/forejt.ics ./gh-pages/

      - name: Commit and push to gh-pages if different
        if: env.changed == 'true'
        run: |
          cd ./gh-pages
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add forejt.ics
          git commit -m "Update Calendar ICS file"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
